# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.3-alpine3.19
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: vanto
      POSTGRES_USER: postgres
    networks:
      - backend-network


# backend service
# running migrations

#  backend:
#    image: 
      
networks:
  backend-network: