@host=http://localhost:5154
@teamId=869b0fd8-aeb0-4bee-af39-06d50fb6b3fc

POST {{host}}/api/teams/{{teamId}}/members
Content-Type: application/json

{
"firstName": "name",
"lastName": "last name",
"email": "email1",
"phoneNumber": "555-444-333"
}
